### ISSUE TITLE
cmake --install doesn't install AntiDuplX

### ISSUE THREAD

**Issue by qarkai** [ermig1979/AntiDuplX#5]
`cmake --install ./build` installs Simd actually. Following files with intermediate dirs were created:
```
CMAKE_INSTALL_PREFIX/include/Simd/Simd*.hpp
CMAKE_INSTALL_PREFIX/lib/libSimd.a
CMAKE_INSTALL_PREFIX/share/simd/simdtargets.cmake
```
Is there specific target to install `AntiDuplX` binary?

**Comment by ermig1979** [comment]
Hi! I fixed this problem

**Comment by qarkai** [comment]
Thank you! Maybe `DESTINATION` should be more conventional `CMAKE_INSTALL_BINDIR` but `bin` works for me too.
