### ISSUE TITLE
Add content to `CMakeLists. txt` to ensure static linking is used during compilation

### ISSUE THREAD

**Issue by NOBB2333** [ermig1979/AntiDuplX#7]
demand:
Add content to `CMakeLists. txt` to ensure static linking is used during compilation

```cmake
#Disable shared libraries and enable static libraries
set(BUILD_SHARED_LIBS OFF)

#Set linker flags for static linking
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -static-libgcc -static-libstdc++")
```
---

God ermig1979, I have been following this project since its first day, which may be the best image plagiarism detection solution on Liunx. I have been trying to migrate to Liunx since I only had `AntiDupl Winform`, but my ability was insufficient and I was unable to succeed. A year ago, after the release of the `AntiDuplX` project, I tried it, but due to the lack of a project, I did not make many applications.

Today, I encountered an issue during using. When using the provided `CMakeLists. txt` for operation, the Build generated file was 77MB. When I copied the file to an internal computer, it prompted me that there were no corresponding dependency projects. After checking with `ldd` (you can use the `ldd` command to check if the generated binary file does indeed contain all necessary dependencies. Static linked binary files will not display external dependency libraries)

```shell
wong@NucBox-G3 ~/D/C/C/AntiDuplX (master)> ldd ./build/AntiDuplX 
   linux-vdso.so.1 (0x00007ffc587e0000)
   libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007411b7c00000)
   libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007411b8a1c000)
   libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007411b89ef000)
   libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007411b7800000)
   /lib64/ld-linux-x86-64.so.2 (0x00007411b8b1a000)
```

After asking `ChatGpt`, the answer is to add the following content to `CMakeLists. txt` to ensure the use of static links during compilation

```cmake
#Disable shared libraries and enable static libraries
set(BUILD_SHARED_LIBS OFF)

#Set linker flags for static linking
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -static-libgcc -static-libstdc++")
```

```cmake
#If your project uses specific libraries, you also need to ensure that the static versions of these libraries are correctly located and linked. You can specify the static version of the library by：

find_library(JPEG_LIBRARY NAMES jpeg PATHS /path/to/static/libs)
find_library(PNG_LIBRARY NAMES png PATHS /path/to/static/libs)
```

**Configure and Compile Project **:

Reconfigure and compile your project to ensure the use of static links:

```shell
mkdir -p build
cmake ./prj/cmake -B ./build -DCMAKE_BUILD_TYPE=Release
cmake --build ./build --config Release --parallel $(nproc)
```

After completion, the result is as follows. At this time, the file size is 80M and static link library is used without affecting system usage:

```shell
wong@NucBox-G3  ~/D/C/C/AntiDuplX (master)> ldd ./ build/AntiDuplX
   not a dynamic executable
```

---
The specific machine parameters are as follows:

|                               |              |
| ----------------------------- | ------------ |
| CPU                           | Inter N100   |
| system                        | Ubuntu 24.04 |
| cmake version                 | 3.28.3       |
| g++ (Ubuntu 13.2.0-23ubuntu4) | 13.2.0       |

---
требовать:
Добавьте содержимое в `CMakeLists. txt`, чтобы гарантировать использование статической компоновки во время компиляции.

```cmake
#Disable shared libraries and enable static libraries
set(BUILD_SHARED_LIBS OFF)

#Set linker flags for static linking
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -static-libgcc -static-libstdc++")
```

Господи ermig1979, я слежу за этим проектом с самого его первого дня, и это, возможно, лучшее решение для обнаружения плагиата изображений в Liunx. Я пытался перейти на Liunx, так как у меня был только AntiDupl Winform, но моих способностей было недостаточно, и мне не удалось добиться успеха. Год назад, после выхода проекта `AntiDuplX`, я попробовал его, но из-за отсутствия проекта многих приложений я не сделал.

Сегодня во время использования столкнулся с проблемой. При использовании предоставленного `CMakeLists. txt` для работы, размер сгенерированного файла сборки составлял 77 МБ. Когда я скопировал файл на внутренний компьютер, мне сообщили, что соответствующих проектов зависимостей нет. После проверки с помощью `ldd` (вы можете использовать команду `ldd`, чтобы проверить, действительно ли сгенерированный двоичный файл содержит все необходимые зависимости. Статические связанные двоичные файлы не будут отображать внешние библиотеки зависимостей)

```shell
wong@NucBox-G3 ~/D/C/C/AntiDuplX (master)> ldd ./build/AntiDuplX 
   linux-vdso.so.1 (0x00007ffc587e0000)
   libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007411b7c00000)
   libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007411b8a1c000)
   libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007411b89ef000)
   libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007411b7800000)
   /lib64/ld-linux-x86-64.so.2 (0x00007411b8b1a000)
```
После запроса ChatGpt ответом будет добавить следующий контент в CMakeLists. txt`, чтобы гарантировать использование статических ссылок во время компиляции.

```cmake
#Disable shared libraries and enable static libraries
set(BUILD_SHARED_LIBS OFF)

#Set linker flags for static linking
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static -static-libgcc -static-libstdc++")
```

```cmake
#Если в вашем проекте используются определенные библиотеки, вам также необходимо убедиться, что статические версии этих библиотек правильно расположены и связаны. Вы можете указать статическую версию библиотеки:

find_library(JPEG_LIBRARY NAMES jpeg PATHS /path/to/static/libs)
find_library(PNG_LIBRARY NAMES png PATHS /path/to/static/libs)
```

**Настройка и компиляция проекта**:
Перенастройте и скомпилируйте проект, чтобы обеспечить использование статических ссылок:

```shell
mkdir -p build
cmake ./prj/cmake -B ./build -DCMAKE_BUILD_TYPE=Release
cmake --build ./build --config Release --parallel $(nproc)
```

После завершения результат следующий. В настоящее время размер файла составляет 80 МБ, и используется статическая библиотека ссылок, не влияющая на использование системы:
```shell
wong@NucBox-G3  ~/D/C/C/AntiDuplX (master)> ldd ./ build/AntiDuplX
   not a dynamic executable
```

**Comment by ermig1979** [comment]
Hi. I added mentioned above options to CMakeLists.txt and running of

     ldd ./build/AntiDuplX

gives

     not a dynamic executable
